name: hello-world
# trigger
on:
  push:
    branches: ["stage"]
# pipeline
jobs:
  print: # job name
  # ejecuta el pipeline en una VM Ubuntu
    runs-on: ubuntu-latest

    # Pasos a ejecutar
    steps:
      - name: print-to-screen
        run: echo "Hello World!"