name: hello-world

on:
 push:
   branches: [ "stage" ]

env:
 TEXT: "Carlos Chacon"

jobs:
 print:
   runs-on: ubuntu-latest
   steps:
     - name: print-to-screen
       run: echo "Hello ${{ env.TEXT }}"
     - name: print-secret
       run: echo "Secret value ${{ secrets.SECRET_VALUE }}"
     - name: The job has succeeded?
       if: ${{ success() }}
       run: return 0
     - name: The job has failed?
       if: ${{ failure() }}
       run: echo "Job fails :("